version: '3.8'

networks:
  weshare-network:
    driver: bridge

services:
  weshare:
    container_name: weshare
    build: .
    networks:
      - weshare-network
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - weshare-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weshare

  mysql:
     image: mysql:8.0.34
     container_name: mysql
     env_file:
       - .env
     ports:
       - "3307:3306"
     networks:
       - weshare-network
     environment:
       MYSQL_ROOT_PASSWORD: pwd
       MYSQL_USER: develop
       MYSQL_PASSWORD: pwd
       MYSQL_DATABASE: weshare
     volumes:
       - type: bind
         source: ./scripts/init_user.sql
         target: /docker-entrypoint-initdb.d/init_user.sql
       - type: bind
         source: ./scripts/init_db.sql
         target: /docker-entrypoint-initdb.d/init_db.sql
       - mysql:/var/lib/mysql

volumes:
  mysql:
