version: '3.8'

networks:
  weshare-network:
    driver: bridge

services:
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=weshare
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - weshare-network

  weshare:
    container_name: weshare
    build: .
    environment:
      - DB_USER=root
      - DB_PASSWORD=pwd
      - DB_HOST=mysql
    networks:
      - weshare-network
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - weshare-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - weshare

volumes:
  mysql_data:
