version: "3.8"
services:
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=weshare
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - weshare-network

  weshare:
    container_name: weshare
    build: .
    environment:
      - DB_USER=root
      - DB_PASSWORD=pwd
      - DB_HOST=mysql
    networks:
      - weshare-network
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine3.17
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./private/certificate.crt:/etc/nginx/certificate.crt:ro
      - ./private/private.key:/etc/nginx/private.key:ro
    restart: always
    networks:
      - my_network

volumes:
  mysql_data:
